"""followers

Revision ID: 623a1e467bab
Revises: ccdd22bf32ae
Create Date: 2022-06-23 15:26:12.010546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623a1e467bab'
down_revision = 'ccdd22bf32ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
